import Header from "@/components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <div className="flex flex-col w-full">
      <Header />
      <main className="mx-auto w-full max-w-5xl">
        <section className="relative flex gap-8">
          {/* 메인 섹션 */}
          {children}
          {/* 사이드 섹션 */}
        </section>
      </main>
      {modal}
    </div>
  );
}
