import Header from "@/components/Header";
import MainContainer from "@/components/MainContainer";
import SideContainer from "@/components/SideContainer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <div className="flex flex-col w-full">
      <Header />
      <main className="mx-auto w-full max-w-5xl">
        <section className="relative flex gap-8 p-6">
          <MainContainer>{children}</MainContainer>
          <SideContainer />
        </section>
      </main>
      {modal}
    </div>
  );
}
