import './globals.css'
import type { Metadata } from 'next'
import { cn } from '@/shared/lib/utils/tail-wind-merge'
import { QueryClientProvider } from '@/app/_providers/query-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased')}>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  )
}
