import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/app/globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import TabProvider from "@/providers/TabProvider";
const notoSansKR = Noto_Sans_KR({ weight: ["500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansKR.className} bg-neutral-400/10 antialiased`}>
        <AuthProvider>
          <QueryProvider>
            <TabProvider>{children}</TabProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
